//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Gleda = new HashSet<Gleda>();
            this.Novost = new HashSet<Novost>();
            this.Glumac = new HashSet<Glumac>();
        }
    
        public int ID_Film { get; set; }
        public string Naziv { get; set; }
        public System.DateTime Datum_izdavanja { get; set; }
        public int Trajanje { get; set; }
        public string Adresa_url { get; set; }
        public byte[] Thumbnail { get; set; }
        public int ID_Redatelj { get; set; }
        public int ID_Zanr { get; set; }
        public int ID_Dobno_ogranicenje { get; set; }
    
        public virtual DobnoOgranicenje DobnoOgranicenje { get; set; }
        public virtual Redatelj Redatelj { get; set; }
        public virtual Zanr Zanr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gleda> Gleda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Novost> Novost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Glumac> Glumac { get; set; }
    }
}
