//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gleda
    {
        public int ID_Gledanje { get; set; }
        public int ID_Film { get; set; }
        public int ID_Korisnik { get; set; }
        public System.DateTime Datum_gledanja { get; set; }
        public Nullable<int> Ocjena { get; set; }
        public string Komentar { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
