//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.Gleda = new HashSet<Gleda>();
        }
    
        public int ID_Korisnik { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Nadimak { get; set; }
        public string Email { get; set; }
        public string Lozinka { get; set; }
        public System.DateTime Datum_izrade_racuna { get; set; }
        public byte[] Slika_profila { get; set; }
        public int ID_Uloga { get; set; }
        public Nullable<int> ID_Roditeljska_zastita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gleda> Gleda { get; set; }
        public virtual RoditeljskaZastita RoditeljskaZastita { get; set; }
        public virtual Uloga Uloga { get; set; }
    }
}
