//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoMaster
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2324_02_DBEntities : DbContext
    {
        public PI2324_02_DBEntities()
            : base("name=PI2324_02_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DobnoOgranicenje> DobnoOgranicenje { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Gleda> Gleda { get; set; }
        public virtual DbSet<Glumac> Glumac { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Novost> Novost { get; set; }
        public virtual DbSet<Redatelj> Redatelj { get; set; }
        public virtual DbSet<RoditeljskaZastita> RoditeljskaZastita { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
        public virtual DbSet<Zanr> Zanr { get; set; }
    }
}
