//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novost
    {
        public int ID_Novost { get; set; }
        public string Naslov { get; set; }
        public System.DateTime Datum_novosti { get; set; }
        public string Opis { get; set; }
        public byte[] Thumbnail { get; set; }
        public int ID_Film { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
